
insert into Counties (CountyName) values ('Albemarle County') 
insert into Counties (CountyName) values ('Alexandria') 	
insert into Counties (CountyName) values ('Alleghany County')
insert into Counties (CountyName) values ('Amelia County') 	
insert into Counties (CountyName) values ('Amherst County') 	
insert into Counties (CountyName) values ('Appomattox County')  	
insert into Counties (CountyName) values ('Arlington County') 	
insert into Counties (CountyName) values ('Augusta County') 	 	
insert into Counties (CountyName) values ('Bath County')  	
insert into Counties (CountyName) values ('Bedford County') 	 	
insert into Counties (CountyName) values ('Bland County') 	 	
insert into Counties (CountyName) values ('Botetourt County')  	
insert into Counties (CountyName) values ('Bristol') 	 	
insert into Counties (CountyName) values ('Brunswick County') 
insert into Counties (CountyName) values ('Buchanan County') 
insert into Counties (CountyName) values ('Buckingham County') 
insert into Counties (CountyName) values ('Buena Vista') 	 	
insert into Counties (CountyName) values ('Campbell County') 
insert into Counties (CountyName) values ('Caroline County') 
insert into Counties (CountyName) values ('Carroll County') 	 	
insert into Counties (CountyName) values ('Charles City County')  	
insert into Counties (CountyName) values ('Charlotte County')  	
insert into Counties (CountyName) values ('Charlottesville')  	
insert into Counties (CountyName) values ('Chesapeake') 	 	
insert into Counties (CountyName) values ('Chesterfield County') 
insert into Counties (CountyName) values ('Clarke County') 	 	
insert into Counties (CountyName) values ('Colonial Heights') 
insert into Counties (CountyName) values ('Covington') 	 	
insert into Counties (CountyName) values ('Craig County') 	 	
insert into Counties (CountyName) values ('Culpeper County')  	
insert into Counties (CountyName) values ('Cumberland County')  	
insert into Counties (CountyName) values ('Danville') 	 	
insert into Counties (CountyName) values ('Dickenson County')  	
insert into Counties (CountyName) values ('Dinwiddie County')  	
insert into Counties (CountyName) values ('Emporia') 	 	
insert into Counties (CountyName) values ('Essex County') 	 	
insert into Counties (CountyName) values ('Fairfax') 	 	
insert into Counties (CountyName) values ('Fairfax County') 	 	
insert into Counties (CountyName) values ('Falls Church') 	 	
insert into Counties (CountyName) values ('Fauquier County') 
insert into Counties (CountyName) values ('Floyd County') 	 	
insert into Counties (CountyName) values ('Fluvanna County') 
insert into Counties (CountyName) values ('Franklin') 	 	
insert into Counties (CountyName) values ('Franklin County') 
insert into Counties (CountyName) values ('Frederick County')  
insert into Counties (CountyName) values ('Fredericksburg') 	 	
insert into Counties (CountyName) values ('Galax') 	 	
insert into Counties (CountyName) values ('Giles County') 
insert into Counties (CountyName) values ('Gloucester County')  	
insert into Counties (CountyName) values ('Goochland County')  	
insert into Counties (CountyName) values ('Grayson County') 	 	
insert into Counties (CountyName) values ('Greene County') 	 	
insert into Counties (CountyName) values ('Greensville County') 
insert into Counties (CountyName) values ('Halifax County') 	 	
insert into Counties (CountyName) values ('Hampton') 	 	
insert into Counties (CountyName) values ('Hanover County') 	 	
insert into Counties (CountyName) values ('Harrisonburg') 	 	
insert into Counties (CountyName) values ('Henrico County') 	 	
insert into Counties (CountyName) values ('Henry County') 	 	
insert into Counties (CountyName) values ('Highland County') 
insert into Counties (CountyName) values ('Hopewell') 	 	
insert into Counties (CountyName) values ('Isle of Wight County') 
insert into Counties (CountyName) values ('James City County') 	
insert into Counties (CountyName) values ('King and Queen County') 	
insert into Counties (CountyName) values ('King George County') 	
insert into Counties (CountyName) values ('King William County') 	
insert into Counties (CountyName) values ('Lancaster County') 	
insert into Counties (CountyName) values ('Lee County') 	 	
insert into Counties (CountyName) values ('Lexington') 	 	
insert into Counties (CountyName) values ('Loudoun County') 	 	
insert into Counties (CountyName) values ('Louisa County') 	 	
insert into Counties (CountyName) values ('Lunenburg County') 
insert into Counties (CountyName) values ('Lynchburg') 	 	
insert into Counties (CountyName) values ('Madison County') 	 	
insert into Counties (CountyName) values ('Manassas') 	 	
insert into Counties (CountyName) values ('Manassas Park') 	 	
insert into Counties (CountyName) values ('Martinsville') 	 	
insert into Counties (CountyName) values ('Mathews County') 	 	
insert into Counties (CountyName) values ('Mecklenburg County') 
insert into Counties (CountyName) values ('Middlesex County')  
insert into Counties (CountyName) values ('Montgomery County') 
insert into Counties (CountyName) values ('Nelson County') 	 	
insert into Counties (CountyName) values ('New Kent County') 
insert into Counties (CountyName) values ('Newport News')  	
insert into Counties (CountyName) values ('Norfolk')  	
insert into Counties (CountyName) values ('Northampton County')
insert into Counties (CountyName) values ('Northumberland County')
insert into Counties (CountyName) values ('Norton') 	 	
insert into Counties (CountyName) values ('Nottoway County')
insert into Counties (CountyName) values ('Orange County') 	 	
insert into Counties (CountyName) values ('Page County') 	 	
insert into Counties (CountyName) values ('Patrick County') 	 	
insert into Counties (CountyName) values ('Petersburg') 	 	
insert into Counties (CountyName) values ('Pittsylvania County')
insert into Counties (CountyName) values ('Poquoson') 	 	
insert into Counties (CountyName) values ('Portsmouth') 	 	
insert into Counties (CountyName) values ('Powhatan County') 
insert into Counties (CountyName) values ('Prince Edward County') 
insert into Counties (CountyName) values ('Prince George County') 
insert into Counties (CountyName) values ('Prince William County') 
insert into Counties (CountyName) values ('Pulaski County') 	 	
insert into Counties (CountyName) values ('Radford')    	
insert into Counties (CountyName) values ('Rappahannock County')  	
insert into Counties (CountyName) values ('Richmond')  	
insert into Counties (CountyName) values ('Richmond County')  
insert into Counties (CountyName) values ('Roanoke')  	
insert into Counties (CountyName) values ('Roanoke County') 	 	
insert into Counties (CountyName) values ('Rockbridge County') 
insert into Counties (CountyName) values ('Rockingham County') 
insert into Counties (CountyName) values ('Russell County') 	 	
insert into Counties (CountyName) values ('Salem') 	 	
insert into Counties (CountyName) values ('Scott County') 
insert into Counties (CountyName) values ('Shenandoah County') 
insert into Counties (CountyName) values ('Smyth County') 	 	
insert into Counties (CountyName) values ('Southampton County') 
insert into Counties (CountyName) values ('Spotsylvania County')  
insert into Counties (CountyName) values ('Stafford County')  
insert into Counties (CountyName) values ('Staunton')  	
insert into Counties (CountyName) values ('Suffolk')  	
insert into Counties (CountyName) values ('Surry County')  	
insert into Counties (CountyName) values ('Sussex County') 	
insert into Counties (CountyName) values ('Tazewell County') 
insert into Counties (CountyName) values ('Virginia Beach')  	
insert into Counties (CountyName) values ('Warren County') 	 	
insert into Counties (CountyName) values ('Washington County')  	
insert into Counties (CountyName) values ('Waynesboro')  	
insert into Counties (CountyName) values ('Westmoreland County') 	
insert into Counties (CountyName) values ('Williamsburg')  	
insert into Counties (CountyName) values ('Winchester')  	
insert into Counties (CountyName) values ('Wise County')  	
insert into Counties (CountyName) values ('Wythe County')  	
insert into Counties (CountyName) values ('York County')  	